# Copyright (c) 2018 Sine Nomine Associates
#
# Install and uninstall with pip.
#
include Makefile.config

.PHONY: install
install:
	$(PIP) install --upgrade .

.PHONY: install-user
install-user:
	$(PIP) install --upgrade --user .

.PHONY: install-dev
install-dev:
	$(PIP) install --editable .

.PHONY: uninstall
uninstall:
	$(PIP) uninstall -y $(NAME)

.PHONY: uninstall-user
uninstall-user:
	$(PIP) uninstall -y $(NAME)

.PHONY: uninstall-dev
uninstall-dev:
	$(PIP) uninstall -y $(NAME)
